apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: njt-eks-petclinic
  region: ap-northeast-2
  version: "1.32"
  tags:
    karpenter.sh/discovery: njt-eks-petclinic

vpc:
  id: vpc-07559628e9d42f744
  securityGroup: sg-04d9b8436983eac27
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-021d99c7d80abd59a
      ap-northeast-2c:
        id: subnet-0483d1fa4aa8e62cc

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

addons: #관리형 addons으로 자동 업데이트
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: metrics-server      # ← 여기에 추가
    version: latest
  - name: eks-pod-identity-agent
    version: latest  

iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: "kube-system"
    serviceAccountName: karpenter
    roleName: njt-eks-petclinic-karpenter
    permissionPolicyARNs:
    - arn:aws:iam::906336681755:policy/KarpenterControllerPolicy-njt-eks-petclinic

iamIdentityMappings:
- arn: "arn:aws:iam::906336681755:role/KarpenterNodeRole-njt-eks-petclinic"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes
  ## If you intend to run Windows workloads, the kube-proxy group should be specified.
  # For more information, see https://github.com/aws/karpenter/issues/5099.
  # - eks:kube-proxy-windows

managedNodeGroups:
- instanceType: t3.medium
  amiFamily: AmazonLinux2023
  name: njt-eks-petclinic-ng
  tags: 
    Name: njt-ec2-petc-eksnode-apn2 
  desiredCapacity: 2
  minSize: 1
  maxSize: 5
  privateNetworking: true
  subnets:
      - subnet-021d99c7d80abd59a
      - subnet-0483d1fa4aa8e62cc



