apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "KarpenterNodeRole-njt-eks-petclinic"
  amiSelectorTerms:
    - alias: "al2023@v20250704"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "njt-eks-petclinic"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "njt-eks-petclinic"

